---
- name: Config Web VM with Docker
  hosts: webservers
  become: true
  tasks:
  - name: Install pip3
    apt:
      name: python3-pip
      state: present
  - name: Install Python Docker Module
    pip:
      name: docker
      state: present
  - name: docker
    apt:
      update_cache: yes
      name: docker.io
      state: present
  - name: install docker container
    docker_container:
      name: dvwa
      image: cyberxsecurity/dvwa
      state: started
      restart_policy: always
      published_ports: 80:80